Comments added

diff --git a/consume b/consume
--- a/consume
+++ b/consume
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+# consume a message from a MQ service using STOMP
+# By Laurent "ker2x" Laborde at http://www.overblog.com/
+#
+# This program is free software. It comes without any warranty, to
+# the extent permitted by applicable law. You can redistribute it
+# and/or modify it under the terms of the Do What The Fuck You Want
+# To Public License, Version 2, as published by Sam Hocevar. See
+# http://sam.zoy.org/wtfpl/COPYING for more details.
+
+# VARIABLES
 MQHOST=
 MQPORT=
 MQQ=
@@ -7,13 +17,13 @@ LOGIN=
 PASS=
 HANDLER=
 
+# Print usage and exit
 usage() {
-cat<<EOF
-    usage : $0 -h hostname -p port -q queuename -c consumerscript [-U user -P password]
-EOF
-exit 1
+    echo "usage : $0 -h hostname -p port -q queuename -c consumerscript [-U user -P password]"
+    exit 1
 }
 
+# Retrieve args and assign to variables
 while getopts "h:p:q:U:P:c:" opt; do
     case $opt in
         h) MQHOST="$OPTARG";;
@@ -27,10 +37,15 @@ while getopts "h:p:q:U:P:c:" opt; do
     esac
 done
 
+# Host, port and queue name are mandatory
 if [[ -z $MQHOST ]] || [[ -z $MQPORT ]] || [[ -z $MQQ ]]
 then
+    echo "ERROR : Host, port and queue name are mandatory"
     usage
 fi
 
+# consume message using socat ( http://www.dest-unreach.org/socat/ )
 socat tcp4:$MQHOST:$MQPORT SYSTEM:"awk --assign usercmd=$HANDLER --assign queue=$MQQ --assign mylogin=$LOGIN --assign mypass=$PASS -f ./stomp-parser.awk"
 
+# KTHXBYE
+exit 0
